name: Test Action from Internal Organization

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - id: hello
        uses: ContosoOrgOpenSource/hello-world-java-action@main
        with:
          who-to-greet: 'Mona the Octocat from Internal Organization'
      - run: echo random-number ${{ steps.hello.outputs.random-number }}
        shell: bash
